name: C++ and Python Ukol 0 Tests

on: [push, pull_request]

jobs:
  python_test:
    runs-on: ubuntu-latest
    if: |
      github.event_name == 'pull_request' || 
      github.event.repository.fork == true || 
      github.ref != 'refs/heads/master'
    steps:
    - uses: actions/checkout@v3
    - name: Install Python dependencies
      run: python3 -m pip install --upgrade pip
    - name: Run Python tests
      run: cd Ukol_0/python && python3 -m unittest discover || exit 1
  cpp_test:
    runs-on: ubuntu-latest
    if: |
      github.event_name == 'pull_request' || 
      github.event.repository.fork == true || 
      github.ref != 'refs/heads/master'
    steps:
    - uses: actions/checkout@v3
    - name: Install C++ dependencies
      run: sudo apt-get update && sudo apt-get install -y cmake g++ libgtest-dev
    - name: Build and run C++ tests
      run: cd Ukol_0/cpp && mkdir -p build && cd build && cmake .. && make && ./mytests || exit 1