name: C++ Ukol 4 Tests

on: [push, pull_request]

jobs:
  cpp_test:
    runs-on: ubuntu-latest
    if: |
      github.event_name == 'pull_request' || 
      github.event.repository.fork == true || 
      github.ref != 'refs/heads/master'
    steps:
    - uses: actions/checkout@v3
    - name: Install C++ dependencies
      run: sudo apt-get update && sudo apt-get install -y cmake g++ libgtest-dev
    - name: Build and run C++ tests
      run: cd Ukol_4 && mkdir -p build && cd build && cmake .. && make && ./mytests || exit 1